
'use strict';

export const PERFORM_LOGIN_ACTION='PERFORM_LOGIN_ACTION';
export const RECEIVE_LOGIN_ACTION='RECEIVE_LOGIN_ACTION';

export const LOADING_DATA_ACTION='LOADING_DATA_ACTION';
export const RECEIVE_DATA_ACTION='RECEIVE_DATA_ACTION';